config/routes.rb
Rails.application.routes.draw do
  root 'epicenter#feed'

  get 'all_users' => 'epicenter#all_users'

  get 'followers' => 'epicenter#followers'

   get 'following' => 'epicenter#following'

  get 'show_user' => 'epicenter#show_user'

  get 'now_following' => 'epicenter#now_following'

  get 'unfollow' => 'epicenter#unfollow'

  resources :tweets
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'tweets_list' =>  'tweets/index'

  get 'tag_tweets' => 'epicenter#tag_tweets'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :tweet_tags
	has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ApplicationRecord
 belongs_to :user
 has_many :tweet_tags
 has_many :tags, through: :tweet_tags

 before_validation :link_check, on: :create


 validates :message, presence: true
 validates :message, length: {maximum: 140, too_long: "A tweet is 140 characters!"}, on: :create

after_validation :apply_link, on: :create

 private

	def link_check
		found_link = false
		if (self.message.include?("http://") || self.message.include?("https://"))
			found_link = true
		end

		if found_link
			arr = self.message.split
			arr.each_with_index do |word, index|
				if word.include?("http")
					self.link = word
					if word.length > 23
					arr[index] = word[0..22]
					end
				end
			end
			self.message = arr.join(" ")
		end
	end
	def apply_link
		arr = self.message.split

		index = arr.map{|x| x.include? "http"}.index(true)

		if index
		  url = arr[index]	
		  arr[index] = "<a href='#{self.link}' target='_blank'>#{url}</a>"

		end


		self.message = arr.join(" ")
	end
end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
	belongs_to :tweet
	belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 has_many :tweets
 serialize :following, Array

 mount_uploader :avatar, AvatarUploader

 validates :username, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

before_action :configure_permitted_parameters, if: :devise_controller?

protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :username, :bio, :location, :avatar, :following])
		devise_parameter_sanitizer.permit(:account_update, keys:[:name, :username, :bio, :location, :avatar, :following])
	end

end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
	before_action :authenticate_user! 

  def following
    @user = User.find(params[:id])

    @users = []

    @user.following.each do |user_id|
      @users.push(User.find(user_id))
    end
 end

  def followers
    @user =User.find(params[:id])

    @users = []

    User.all.each do |user|
      if user.following.include?(@user.id)
        @users.push(user)
      end
    end
  end

 

  def all_users
    @users = User.all
  end

  def tag_tweets
    @tag = Tag.find(params[:id])

  end
  
  def feed
    @tweet = Tweet.new
  	@following_tweets = []

  	Tweet.all.each do |tweet|
  		if (current_user.following.include?(tweet.user_id) || current_user.id == tweet.user_id)
  			@following_tweets.push(tweet)
  		end
  	end
  	@following_tweets.reverse!
  end

  def show_user
  	@user = User.find(params[:id])
    @followers_count = 0

User.all.each do |user|
      if user.following.include?(@user.id)
        @followers_count +=1
      end
    end
    @followers_count
  end
  
  def now_following
  	current_user.following.push(params[:id].to_i)
  	current_user.save

  	redirect_to show_user_path(id: params[:id])


  end

  def unfollow
  	current_user.following.delete(params[:id].to_i)
  	current_user.save

  	redirect_to show_user_path(id: params[:id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! 

  include TweetsHelper
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save

        @tweet = get_tagged(@tweet)
        @tweet.save

        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper

	def get_tagged(tweet)
		message_arr = tweet.message.split

        message_arr.each_with_index do |word, index|
          if (word[0] == "#")
            if(Tag.pluck(:phrase).include?(word.downcase))
              tag = Tag.find_by(phrase: word.downcase)
            else
              tag = Tag.create(phrase: word.downcase)
            end
            tweet_tag = TweetTag.create(tweet_id: tweet.id, tag_id: tag.id)
            message_arr[index] = "<a href= '/tag_tweets?id=#{tag.id}'>#{word}</a>"
          end
        end
        tweet.message = message_arr.join(" ")

        
        return tweet

       # tweet.update(message: message_arr.join(" "))
    end
end

app/views/epicenter/_user_list.html.erb
<div class="row">
	<% @users.each do |user| %>
	 <div class = "col-md-3">
	 	<div class = "well">
	 	  <div class = "row">
	 	  <div class = "col-md-6">
	 	  	<% if !user.avatar.file.nil? %>
	 	  		<%= image_tag user.avatar.url, class: "img-responsive" %>
	 	  	<% end %>
	 	  </div>

	 	  <div class = "col-md-6">
	 	  	<p>
	 	  		<% if current_user.id != user.id %>
		<% if current_user.following.include?(user.id) %>
			<%= link_to "Following", unfollow_path(id: user.id), class: "btn btn-success", id:"unfollow_btn" %>
		<% else %>
			<%= link_to "Follow", now_following_path(id: user.id), class: "btn btn-success" %>

		<% end %>
	<% end %>
	 	  	</p>
	 	  </div>
	 	</div>

	 	<div class = "row">
	 		<div class = "col-md-8 offset-md-2">
	 			<%= link_to show_user_path(id: user.id) do %>
	 			<h3><%= user.name %></h3>
	 			<p>@<%= user.username %></p>
	 			<% end %>
	  		<p>
	  			<%= user.bio %>
	  		</p>
	  	</div>
	  </div>
	  </div>
	</div>
  <% end %>
</div>

app/views/epicenter/all_users.html.erb
<h3>All Users:</h3>

<%= render "user_list" %>

app/views/epicenter/feed.html.erb
<div class="row">
	<div class="col-sm-2">
		<h2> Topics for You </h2>
			<ul>
				<li>
					<a href="#"> #Puppies </a>
				</li>
				<li>
					<a href="#"> #Kittens </a>
				</li>
				<li>
					<a href="#"> #Programming </a>
				</li>
				<li>
					<a href="#"> #Ruby </a>
				</li>
			</ul>
	</div>

	<div class="col-md-3 col-md-offset-1">
		<h2>@<%= current_user.username %>'s Feed</h2>
		<p><a href="#">load new tweets</a></p>
		<%= render 'tweets/form.html.erb', tweet: @tweet %>
		<div>
			<% @following_tweets.each do |tweet| %>
				<div class="well">
					<p>
						<% if tweet.user.avatar.url %>
						<%= image_tag tweet.user.avatar.url, size: 40 %>
						<% end %>
						<%= link_to tweet.user.name, show_user_path(id: tweet.user_id) %>
						@<%= link_to tweet.user.username, show_user_path(id: tweet.user_id) %>
						-<%= (time_ago_in_words(tweet.created_at) + " ago") if Time.now - tweet.created_at <86400 %>
						<%= (tweet.created_at.strftime("%b %e")) if Time.now - tweet.created_at >=86400 %>
					</p>
					<p><%= tweet.message.html_safe %></p>
				</div>
		  <% end %>
		</div>
	</div>

<div class="col-sm-2">
	<h2> Who to Follow </h2>
	<ul>
		<li>
			<a href="#"> Barack Obama </a>
		</li>
		<li>
			<a href="#"> Todd Lewis </a>
		</li>
		<li>
			<a href="#"> Mick Jagger </a>
		</li>
		<li>
			<a href="#"> Ozzy Osbourne </a>
		</li>
	</ul>


</div>
</div>

app/views/epicenter/followers.html.erb
<h3><%= @user.name %>'s followers are:</h3>

<%= render 'user_list' %>

app/views/epicenter/following.html.erb
<h3><%= @user.name %> is following: </h3>

<%= render 'user_list' %>

app/views/epicenter/now_following.html.erb
<h1>Epicenter#now_following</h1>
<p>Find me in app/views/epicenter/now_following.html.erb</p>

app/views/epicenter/show_user.html.erb
<h2>@<%= @user.username %>'s Profile</h2>
<p><%= @user.name %> </p>
<p><%= @user.location %> </p>
<p><%= @user.bio %> </p>

<p>
	# of Tweets: <%= @user.tweets.length %>
</p>
<p>
	<%= link_to "following:" + @user.following.length.to_s, following_path(id: @user.id) %>
</p>
<p>
	<%= link_to "followers:" + @followers_count.to_s, followers_path(id: @user.id) %>
</p>

<div>
	<% if current_user.id != @user.id %>
		<% if current_user.following.include?(@user.id) %>
			<%= link_to "Following", unfollow_path(id: @user.id), class: "btn btn-success", id:"unfollow_btn" %>

		<% else %>
			<%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-success" %>
		<% end %>
	<% end %>
</div>
<br>

<div>
  <% @user.tweets.each do |tweet| %>
		<div class="well">
			<p>@<%= link_to tweet.user.username, show_user_path(id: tweet.user_id) %> </p>
			<p><%= tweet.message.html_safe %></p>
		</div>
	<% end %>
</div>

app/views/epicenter/tag_tweets.html.erb
<h1><%= @tag.phrase %></h1>

<div class="row">
	<div>
		<% @tag.tweets.order(created_at: :desc).each do |tweet| %>
		<p>
			<strong><%= tweet.user.name + " @" + tweet.user.username %></strong>
			<br>
			<%= time_ago_in_words(tweet.created_at) %>
		</p>
		<p>
			<%= tweet.message.html_safe %>
		</p>
		<% end %>
	</div>
</div>

app/views/epicenter/unfollow.html.erb
<h1>Epicenter#unfollow</h1>
<p>Find me in app/views/epicenter/unfollow.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweeter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Ubuntu:400,500,700" rel="stylesheet">

  </head>

  <body>
  	<!-- app/views/layouts/application.html.erb -->
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Home", root_path, class: "navbar-brand" %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
        	<% if user_signed_in? %>
          <li><%= link_to "Tweet", new_tweet_path %></li>
          <li><%= link_to "All Users", all_users_path %></li>
        	<% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <% if current_user.avatar.blank? == false %>
                  <%= image_tag current_user.avatar.url, size:50, class: "user-pic-nav" %>
                <% end %> 
                Signed in as: @<%= current_user.username %><span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
    <div class="container">
    <%= yield %>
    </div>
</body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message, id: :tweet_message, class:"form-control", placeholder:"What's happening?" %>
  </div>

  <div class="field"> 
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit "Tweet", class:"btn btn-warning"%>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table class="table">
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message.html_safe %></td>
        <td>@<%=link_to tweet.user.username, show_user_path(id: tweet.user_id) %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message.html_safe %>
</p>

<p>
  <strong>User:</strong>
  <%= link_to "@" + @tweet.user.username, show_user_path(id: @tweet.user_id) %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>